In [6]:
import os
os.chdir("C:/Users/hp/Desktop")
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.compose import ColumnTransformer # Here is the one


from sklearn.model_selection import train_test_split

import keras
from keras.models import Sequential
from keras.layers import Dense

from sklearn.metrics import confusion_matrix


In [7]:
df = pd.read_csv("Churn_Modelling.csv")

In [8]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [9]:
X = df.iloc[:, 3:13].values
y = df.iloc[:, 13].values

In [10]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [11]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.compose import ColumnTransformer # Here is the one

labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])

labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])

In [12]:
ct = ColumnTransformer([("Country", OneHotEncoder(), [1])], remainder = 'passthrough')

X = ct.fit_transform(X)
X = X[:, 1:]


In [13]:
X

array([[0.0, 0.0, 619, ..., 1, 1, 101348.88],
       [0.0, 1.0, 608, ..., 0, 1, 112542.58],
       [0.0, 0.0, 502, ..., 1, 0, 113931.57],
       ...,
       [0.0, 0.0, 709, ..., 0, 1, 42085.58],
       [1.0, 0.0, 772, ..., 1, 0, 92888.52],
       [0.0, 0.0, 792, ..., 1, 0, 38190.78]], dtype=object)

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)


In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [16]:

classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)


Epoch 1/100
8000/8000 [==============================] - 6s 694us/step - loss: 0.4791 - acc: 0.7960
Epoch 2/100
8000/8000 [==============================] - 3s 402us/step - loss: 0.4263 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 3s 403us/step - loss: 0.4203 - acc: 0.8067
Epoch 4/100
8000/8000 [==============================] - 3s 386us/step - loss: 0.4171 - acc: 0.8242
Epoch 5/100
8000/8000 [==============================] - 3s 401us/step - loss: 0.4148 - acc: 0.8279
Epoch 6/100
8000/8000 [==============================] - 3s 421us/step - loss: 0.4133 - acc: 0.8294
Epoch 7/100
8000/8000 [==============================] - 3s 432us/step - loss: 0.4118 - acc: 0.8306
Epoch 8/100
8000/8000 [==============================] - 3s 397us/step - loss: 0.4107 - acc: 0.8339
Epoch 9/100
8000/8000 [==============================] - 3s 388us/step - loss: 0.4098 - acc: 0.8322
Epoch 10/100
8000/8000 [==============================] - 3s 384us/step - loss: 0.4087 - acc: 0.8337

8000/8000 [==============================] - 3s 396us/step - loss: 0.4010 - acc: 0.8354
Epoch 82/100
8000/8000 [==============================] - 3s 405us/step - loss: 0.4008 - acc: 0.8337
Epoch 83/100
8000/8000 [==============================] - 3s 401us/step - loss: 0.4011 - acc: 0.8359 0s - loss: 0.3994 - 
Epoch 84/100
8000/8000 [==============================] - 3s 384us/step - loss: 0.4004 - acc: 0.8364
Epoch 85/100
8000/8000 [==============================] - 4s 439us/step - loss: 0.4006 - acc: 0.8340
Epoch 86/100
8000/8000 [==============================] - 4s 444us/step - loss: 0.4010 - acc: 0.8345
Epoch 87/100
8000/8000 [==============================] - 4s 450us/step - loss: 0.4004 - acc: 0.8359
Epoch 88/100
8000/8000 [==============================] - 4s 446us/step - loss: 0.4009 - acc: 0.8359 0s - loss: 0.4009 - ac
Epoch 89/100
8000/8000 [==============================] - 4s 445us/step - loss: 0.4007 - acc: 0.8350
Epoch 90/100
8000/8000 [==============================] - 3s

In [19]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)


In [20]:
#from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)


In [21]:
cm

array([[1551,   44],
       [ 279,  126]], dtype=int64)

In [22]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])